# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Me\Dropbox\Python\content_engineer_studio\ContentEngineerStudio\pqt_test_designs\ce_studio.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1511, 808)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(10, 0))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.sidebar = QtWidgets.QScrollArea(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar.sizePolicy().hasHeightForWidth())
        self.sidebar.setSizePolicy(sizePolicy)
        self.sidebar.setMinimumSize(QtCore.QSize(20, 0))
        self.sidebar.setMaximumSize(QtCore.QSize(20, 16777215))
        self.sidebar.setWidgetResizable(True)
        self.sidebar.setObjectName("sidebar")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 18, 784))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.sidebar.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.sidebar, 0, 0, 4, 1)
        self.flows = QtWidgets.QScrollArea(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flows.sizePolicy().hasHeightForWidth())
        self.flows.setSizePolicy(sizePolicy)
        self.flows.setMinimumSize(QtCore.QSize(150, 0))
        self.flows.setWidgetResizable(True)
        self.flows.setObjectName("flows")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 331, 755))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.flows.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.flows, 1, 2, 3, 1)
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 0, 2, 1, 1)
        self.chat = QtWidgets.QScrollArea(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat.sizePolicy().hasHeightForWidth())
        self.chat.setSizePolicy(sizePolicy)
        self.chat.setMinimumSize(QtCore.QSize(450, 0))
        self.chat.setWidgetResizable(True)
        self.chat.setObjectName("chat")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 448, 784))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.chat.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.chat, 0, 1, 4, 1)
        self.analysis = QtWidgets.QTextEdit(Form)
        self.analysis.setObjectName("analysis")
        self.gridLayout.addWidget(self.analysis, 2, 3, 2, 2)
        self.canned = QtWidgets.QTableWidget(Form)
        self.canned.setGridStyle(QtCore.Qt.SolidLine)
        self.canned.setRowCount(0)
        self.canned.setColumnCount(0)
        self.canned.setObjectName("canned")
        self.canned.horizontalHeader().setVisible(False)
        self.canned.horizontalHeader().setCascadingSectionResizes(False)
        self.canned.horizontalHeader().setHighlightSections(True)
        self.canned.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.canned, 0, 3, 2, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
